// Generated by Hive CE
// Do not modify
// Check in to version control
// This file is generated automatically and should be checked into version control.

import 'package:data_provider/data_provider.dart';
import 'package:hive_ce/hive.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(OperationMapAdapter());
    registerAdapter(OrderMapAdapter());
  }
}
