name: user_repository
description: Dart package which manages the user domain.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  uuid: ^4.5.1
  equatable: ^2.0.7

dev_dependencies:
  lints: ^5.1.1
