name: user_repository
description: Dart package which manages the user domain.
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  uuid: ^4.5.1
  equatable: ^2.0.7

dev_dependencies:
  lints: ^5.0.0
