version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "reviewer1"
      - "reviewer2"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "reviewer1"
      - "reviewer2"
