name: dap_foreman_assis
description: Mobile application for sewers and manufactures
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  animated_button_bar: ^1.0.0
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.4
  data_provider:
    path: packages/data_provider
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/