name: dap_foreman_assis
description: Mobile application for sewers and manufactures
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.4
  data_provider:
    path: packages/data_provider
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
