name: dap_foreman_assis
description: Mobile application for sewers and manufactures
version: 1.0.0+1
publish_to: none

includes: packages/data_provider/lib/src/hive/hive_adapters.g.yaml
environment:
  sdk: ^3.6.0

dependencies:
  animated_button_bar: ^1.0.0
  app_ui:
    path: packages/app_ui
  auth_repository:
    path: packages/auth_repository
  bloc: ^8.1.4
  data_provider:
    path: packages/data_provider
  equatable: ^2.0.7
  file_picker: ^8.1.7
  firebase_analytics: ^11.4.0
  firebase_crashlytics: ^4.3.0
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  formz: ^0.8.0
  hive_ce: ^2.9.0
  hive_ce_flutter: ^2.1.0
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  persistent_storage:
    path: ./packages/storage/persistent_storage
  secure_storage:
    path: ./packages/storage/secure_storage
  shared_preferences: ^2.3.5
  storage:
    path: ./packages/storage/storage
  syncfusion_flutter_xlsio: ^28.1.38
  user_repository:
    path: packages/user_repository

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
