name: data_provider
description: A package which handle 3rd layer data from out.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.7.0
  equatable: ^2.0.7
  hive: ^2.2.3
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
dev_dependencies:
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  json_serializable: ^6.9.0

  test: ^1.25.8
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - assets/local_employees.json
    - assets/local_operations.json
    - assets/local_orders.json
